server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: TestJWt
  redis:
    port: 6739
    host: 10.7.129.81
    password: yeiD7tho
    database: 8
jwt:
  key: dGVzdGp3dHRlc3Rqd3R0ZXN0and0dGVzdGp3dHRlc3Rqd3R0ZXN0and0dGVzdGp3dHRlc3Rqd3R0ZXN0and0
  expire: 3600000
  issuer: TestJWt